#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S) {
  long long uniq = 1;
  for (long long i = 0; i < N - 1; i++) {
    if (S[i] != S[i + 1]) {
      uniq += 1;
    }
  }
  cout << uniq << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  std::string S;
  std::cin >> S;
  solve(N, S);
  return 0;
}
