#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";
// const string words[4] = {"dreamer", "eraser", "dream", "erase"};

// bool traverse(string S) {
//   if (S.empty())
//     return true;
//   for (string w : words) {
//     if (S.find(w) == -1)
//       continue;
//     string s(S);
//     if (traverse(s.erase(0, w.size()))) {
//       return true;
//     }
//   }
//   return false;
// }

void solve(std::string S) {
  //   if (traverse(S))
  //     cout << YES << endl;
  //   else
  //     cout << NO << endl;
  regex re("(?:dreamer|eraser|dream|erase)+");
  smatch match;
  if (regex_match(S, match, re))
    cout << YES << endl;
  else
    cout << NO << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  std::string S;
  std::cin >> S;
  solve(S);
  return 0;
}
