#include <bits/stdc++.h>
using namespace std;

const long long MOD = 2;

void solve(long long N, std::vector<long long> A) {
  bool odd = true;
  long long count = 0;
  while (odd) {
    for (long long i = 0; i < N; i++) {
      if (A[i] % 2 != 0) {
        odd = false;
        goto OUT;
      }
      A[i] /= 2;
    }
    count++;
  }
OUT:
  cout << count << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  std::vector<long long> A(N);
  for (int i = 0; i < N; i++) {
    scanf("%lld", &A[i]);
  }
  solve(N, std::move(A));
  return 0;
}
