#include <bits/stdc++.h>
using namespace std;

void solve(long long N, long long Y) {
  for (long long x = N; x >= 0; x--) {
    long long _x = (x * 10000);
    if (_x > Y)
      continue;
    for (long long y = N - x; y >= 0; y--) {
      long long _y = (y * 5000);
      if (_x + _y > Y)
        continue;
      long long z = N - x - y;
      long long _z = (z * 1000);
      if (_x + _y + _z == Y) {
        cout << x << " " << y << " " << z << endl;
        return;
      }
    }
  }
  cout << "-1 -1 -1" << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  long long Y;
  scanf("%lld", &Y);
  solve(N, Y);
  return 0;
}
